version: '3'

services:
  ideas-app:
    image: ideas-app:dev
    container_name: ideas-app
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4000:3000
      - 9229:9229
    restart: always
    volumes: 
      - ../..:/usr/src/app
      - /usr/src/app/node_modules
    networks: 
      - ideas-app
networks: 
  ideas-app: